name: Build
on: [push]
jobs:
  arduino-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32s3
          sketch-paths: ./
          libraries: TinyGPSPlus, ESP32Servo, Electronic Cats MPU6050, Adafruit BMP280 Library, HMC5883L
          
