- name: Compile sketch
  uses: arduino/compile-sketches@v1
  with:
    fqbn: esp32:esp32:esp32s3
    platforms: |
      - name: esp32:esp32
        source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    sketch-paths: |
      ./Done.ino
    verbose: true
